# Generated by Django 2.0.7 on 2020-02-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
