# Generated by Django 3.0.3 on 2020-03-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_petservice_idservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('roomNumber', models.IntegerField()),
                ('idPet', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
