# Generated by Django 3.0.3 on 2020-03-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petservice',
            name='idPet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
        migrations.AlterField(
            model_name='petservice',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Service'),
        ),
        migrations.AlterField(
            model_name='room',
            name='idPet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
    ]
